### ISSUE TITLE
Build failure: "Forward declaration of class cannot have a nested name specifier"

### ISSUE THREAD

**Issue by galbus** [num3ric/Cinder-Skinning#5]
On my new system I get a "Semantic Issue" that "Forward declaration of class cannot have a nested name specifier".

The line it doesn't like is Blocks/Skinning/include/ModelSourceAssimp.h:13

```
class model::Node;
```

This happens on the sample files, and also on a new Tinderbox project with Skinning added and no code changes.

OSX 10.9
Xcode Version 5.1 (5B130a)

```
gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/c++/4.2.1
Apple LLVM version 5.1 (clang-503.0.38) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.0.2
Thread model: posix
```

![screen shot 2014-03-23 at 11 01 55](https://f.cloud.github.com/assets/665537/2493099/d724a81c-b27a-11e3-861f-76821b1116ed.png)

**Comment by BanTheRewind** [comment]
This should work, no?

namespace model {

class Node;

}

Sent from Windows Mail

From: Stuart McAlpine
Sent: ‎Sunday‎, ‎March‎ ‎23‎, ‎2014 ‎4‎:‎14‎ ‎AM
To: num3ric/Cinder-Skinning

On my new system I get a "Semantic Issue" that "Forward declaration of class cannot have a nested name specifier".

The line it doesn't like is Blocks/Skinning/include/ModelSourceAssimp.h:13
class model::Node;

This happens on the sample files, and also on a new Tinderbox project with Skinning added and no code changes.

OSX 10.9
Xcode Version 5.1 (5B130a)
gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/c++/4.2.1
Apple LLVM version 5.1 (clang-503.0.38) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.0.2
Thread model: posix

 screen shot 2014-03-23 at 11 01 55

**Comment by num3ric** [comment]
Ah yes apologies, not sure what happened there.

I removed them and other redundant forward declarations in this commit: 8696149360c033f20cae4eeb0cb5812aec76e827 Most are already forward-declared in ModelIO.h anyways.

It should be fixed now in master now.

**Comment by galbus** [comment]
Nice one - that works for me now.

Good work on the Block too. Thanks. :)
