### ISSUE TITLE
Query | Is this project still active?

### ISSUE THREAD

**Issue by vinjn** [num3ric/Cinder-Skinning#6]
I'd like to use it with the latest Cinder :)

**Comment by num3ric** [comment]
Hi @vinjn,

I just pushed the work I had done while learning/porting to glNext (also adding more samples and functionality). Unfortunately, I am not maintaining or updating this block anymore. I am privately using the FBX SDK instead (in a **complete** rewrite), but haven't had the chance to make enough progress to publish yet.

These updates should definitely give you a good start. I just tested the Seymour sample, and it seems to be running.

**Comment by vinjn** [comment]
Thx, closing.
